[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "cosmonum"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["numpy", "scipy"]

[project.optional-dependencies]
dev = ["pytest", "matplotlib", "jupyterlab", "nbconvert", "ipykernel"]

[tool.setuptools]
packages = ["cosmonum"]

[tool.setuptools.package-data]
cosmonum = ["data/*.txt"]

[tool.pytest.ini_options]
testpaths = ["tests"]
